---
- name: Demo playbook to test callback plugin - Deployment
  hosts: client
  tasks:

    
  - name: Install httpd package
    dnf:
      name: httpd
      state: latest
    
  - name: Start and enable httpd service
    service:
      name: httpd
      enabled: true
      state: started

  - name: Create a custom index.html file
    copy:
      dest: /var/www/html/index.html
      content: |
        Enable SysAdmin Demo:
        Ansible Profiling with Callback Plugin
        Custom Web Page

  - firewalld:
      service: https
      permanent: true
      state: enabled

  - firewalld:
      service: http
      permanent: true
      state: enabled

  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded
